modLoader="javafml"
loaderVersion="[47,)"
license="Academic Free License v3.0"

[[mods]]
modId="display"
version="1.1.0"
displayName="Items Displayed"
credits="Jusey1, Freedinner"
displayURL="https://legacy.curseforge.com/minecraft/mc-mods/items-displayed"
authors="Jusey1, Freedinner"
description="Allows the display of specific items."

[[dependencies.display]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="NONE"
    side="BOTH"




