modLoader="javafml"
loaderVersion="[47,)"
license="GNU General Public License version 3 (GPLv3)"

[[mods]]
modId="display"
version="1.3.2"
displayName="Items Displayed"
displayURL="https://legacy.curseforge.com/minecraft/mc-mods/items-displayed"
logoFile="logo.png"
credits="Jusey1, Freedinner"
authors="Jusey1, Freedinner"
description="Allows the display of specific items."

[[dependencies.display]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="NONE"
    side="BOTH"




